---
- name: Upgrade apt packages
  apt:
    update_cache: yes
    upgrade: yes

- import_tasks: setup-alt-user.yml
  when: alt_user_name

- import_tasks: secure-sudo.yml

- import_tasks: secure-ssh.yml

- import_tasks: setup-firewall.yml

- import_tasks: setup-fail2ban.yml
