---
- name: Upgrade apt packages
  apt:
    update_cache: yes
    upgrade: yes

- import_tasks: setup-users.yml

- import_tasks: secure-ssh.yml

- import_tasks: setup-firewall.yml

- import_tasks: setup-fail2ban.yml
