---
- import_tasks: raspi-config.yml

- name: Install useful packages
  apt:
    pkg:
      - vim
      - git

- name: Allow ll alias for alternative user
  replace:
    path: "/home/pi/.bashrc"
    regexp: "#alias ll='ls -l'"
    replace: "alias ll='ls -l'"

- name: Change the password of the default pi user
  user:
    name: pi
    password: "{{ pi_password_custom_enc }}"